import type { SupportedLocale } from '../locales/types';

export interface FeedbackWidgetCopy {
    buttonQuestion: string;
    buttonAriaLabel: string;
    closeLabel: string;
    eyebrow: string;
    title: string;
    intro: string;
    yes: string;
    notReally: string;
    feedbackLabel: string;
    feedbackPlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    submit: string;
    chooseRating: string;
    negativeRequired: string;
    captchaRequired: string;
    captchaFailed: string;
    success: string;
    failure: string;
}

const feedbackCopy: Record<SupportedLocale, FeedbackWidgetCopy> = {
    en: {
        buttonQuestion: 'Do you like this page?',
        buttonAriaLabel: 'Do you like this page? Give feedback',
        closeLabel: 'Close feedback form',
        eyebrow: 'Page feedback',
        title: 'Do you like this page?',
        intro: 'Tell us what worked, or what you expected, wanted changed, or wanted added.',
        yes: 'Yes',
        notReally: 'Not really',
        feedbackLabel: 'What should we change or add?',
        feedbackPlaceholder: 'Short, honest feedback is enough.',
        emailLabel: 'Email optional',
        emailPlaceholder: 'Only if you want a reply',
        submit: 'Send feedback',
        chooseRating: 'Please choose yes or not really.',
        negativeRequired: 'Please tell us what you expected, wanted changed, or wanted added.',
        captchaRequired: 'Please complete the captcha.',
        captchaFailed: 'Captcha verification failed. Please try again.',
        success: 'Thanks - your feedback was sent.',
        failure: 'Failed to send feedback.',
    },
    sk: {
        buttonQuestion: 'Páči sa vám táto stránka?',
        buttonAriaLabel: 'Páči sa vám táto stránka? Pošlite spätnú väzbu',
        closeLabel: 'Zavrieť formulár spätnej väzby',
        eyebrow: 'Spätná väzba k stránke',
        title: 'Páči sa vám táto stránka?',
        intro: 'Napíšte nám, čo fungovalo, alebo čo ste očakávali, chceli zmeniť či pridať.',
        yes: 'Áno',
        notReally: 'Skôr nie',
        feedbackLabel: 'Čo by sme mali zmeniť alebo pridať?',
        feedbackPlaceholder: 'Stačí krátna, úprimná spätná väzba.',
        emailLabel: 'Email nepovinný',
        emailPlaceholder: 'Len ak chcete odpoveď',
        submit: 'Odoslať spätnú väzbu',
        chooseRating: 'Vyberte, prosím, áno alebo skôr nie.',
        negativeRequired: 'Napíšte nám, prosím, čo ste očakávali, chceli zmeniť alebo pridať.',
        captchaRequired: 'Dokončite, prosím, captcha overenie.',
        captchaFailed: 'Captcha overenie zlyhalo. Skúste to znova.',
        success: 'Ďakujeme - spätná väzba bola odoslaná.',
        failure: 'Spätnú väzbu sa nepodarilo odoslať.',
    },
    cs: {
        buttonQuestion: 'Líbí se vám tato stránka?',
        buttonAriaLabel: 'Líbí se vám tato stránka? Pošlete zpětnou vazbu',
        closeLabel: 'Zavřít formulář zpětné vazby',
        eyebrow: 'Zpětná vazba ke stránce',
        title: 'Líbí se vám tato stránka?',
        intro: 'Napište nám, co fungovalo, nebo co jste čekali, chtěli změnit či přidat.',
        yes: 'Ano',
        notReally: 'Spíš ne',
        feedbackLabel: 'Co bychom měli změnit nebo přidat?',
        feedbackPlaceholder: 'Stačí krátká, upřímná zpětná vazba.',
        emailLabel: 'Email nepovinný',
        emailPlaceholder: 'Jen pokud chcete odpověď',
        submit: 'Odeslat zpětnou vazbu',
        chooseRating: 'Vyberte prosím ano nebo spíš ne.',
        negativeRequired: 'Napište nám prosím, co jste čekali, chtěli změnit nebo přidat.',
        captchaRequired: 'Dokončete prosím captcha ověření.',
        captchaFailed: 'Captcha ověření selhalo. Zkuste to prosím znovu.',
        success: 'Děkujeme - zpětná vazba byla odeslána.',
        failure: 'Zpětnou vazbu se nepodařilo odeslat.',
    },
    de: {
        buttonQuestion: 'Gefällt dir diese Seite?',
        buttonAriaLabel: 'Gefällt dir diese Seite? Feedback geben',
        closeLabel: 'Feedbackformular schließen',
        eyebrow: 'Feedback zur Seite',
        title: 'Gefällt dir diese Seite?',
        intro: 'Sag uns, was gut war oder was du erwartet, geändert oder ergänzt hättest.',
        yes: 'Ja',
        notReally: 'Nicht wirklich',
        feedbackLabel: 'Was sollten wir ändern oder hinzufügen?',
        feedbackPlaceholder: 'Kurzes, ehrliches Feedback reicht.',
        emailLabel: 'E-Mail optional',
        emailPlaceholder: 'Nur wenn du eine Antwort möchtest',
        submit: 'Feedback senden',
        chooseRating: 'Bitte wähle Ja oder Nicht wirklich.',
        negativeRequired: 'Bitte sag uns, was du erwartet, geändert oder ergänzt hättest.',
        captchaRequired: 'Bitte schließe das Captcha ab.',
        captchaFailed: 'Captcha-Prüfung fehlgeschlagen. Bitte versuche es erneut.',
        success: 'Danke - dein Feedback wurde gesendet.',
        failure: 'Feedback konnte nicht gesendet werden.',
    },
    fr: {
        buttonQuestion: 'Aimez-vous cette page ?',
        buttonAriaLabel: 'Aimez-vous cette page ? Donner votre avis',
        closeLabel: 'Fermer le formulaire de feedback',
        eyebrow: 'Avis sur la page',
        title: 'Aimez-vous cette page ?',
        intro: 'Dites-nous ce qui a marché, ou ce que vous attendiez, vouliez changer ou ajouter.',
        yes: 'Oui',
        notReally: 'Pas vraiment',
        feedbackLabel: 'Que devrions-nous changer ou ajouter ?',
        feedbackPlaceholder: 'Un avis court et honnête suffit.',
        emailLabel: 'Email facultatif',
        emailPlaceholder: 'Seulement si vous voulez une réponse',
        submit: 'Envoyer l’avis',
        chooseRating: 'Veuillez choisir oui ou pas vraiment.',
        negativeRequired: 'Dites-nous ce que vous attendiez, vouliez changer ou ajouter.',
        captchaRequired: 'Veuillez compléter le captcha.',
        captchaFailed: 'La vérification captcha a échoué. Réessayez.',
        success: 'Merci - votre avis a été envoyé.',
        failure: 'Impossible d’envoyer l’avis.',
    },
    es: {
        buttonQuestion: '¿Te gusta esta página?',
        buttonAriaLabel: '¿Te gusta esta página? Enviar comentarios',
        closeLabel: 'Cerrar formulario de comentarios',
        eyebrow: 'Comentarios de la página',
        title: '¿Te gusta esta página?',
        intro: 'Cuéntanos qué funcionó o qué esperabas, querías cambiar o añadir.',
        yes: 'Sí',
        notReally: 'No mucho',
        feedbackLabel: '¿Qué deberíamos cambiar o añadir?',
        feedbackPlaceholder: 'Basta con un comentario breve y honesto.',
        emailLabel: 'Email opcional',
        emailPlaceholder: 'Solo si quieres una respuesta',
        submit: 'Enviar comentarios',
        chooseRating: 'Elige sí o no mucho.',
        negativeRequired: 'Cuéntanos qué esperabas, querías cambiar o añadir.',
        captchaRequired: 'Completa el captcha.',
        captchaFailed: 'La verificación del captcha falló. Inténtalo de nuevo.',
        success: 'Gracias - tus comentarios se enviaron.',
        failure: 'No se pudieron enviar los comentarios.',
    },
    it: {
        buttonQuestion: 'Ti piace questa pagina?',
        buttonAriaLabel: 'Ti piace questa pagina? Lascia un feedback',
        closeLabel: 'Chiudi il modulo di feedback',
        eyebrow: 'Feedback sulla pagina',
        title: 'Ti piace questa pagina?',
        intro: 'Dicci cosa ha funzionato o cosa ti aspettavi, volevi cambiare o aggiungere.',
        yes: 'Sì',
        notReally: 'Non molto',
        feedbackLabel: 'Cosa dovremmo cambiare o aggiungere?',
        feedbackPlaceholder: 'Basta un feedback breve e sincero.',
        emailLabel: 'Email facoltativa',
        emailPlaceholder: 'Solo se vuoi una risposta',
        submit: 'Invia feedback',
        chooseRating: 'Scegli sì o non molto.',
        negativeRequired: 'Dicci cosa ti aspettavi, volevi cambiare o aggiungere.',
        captchaRequired: 'Completa il captcha.',
        captchaFailed: 'Verifica captcha non riuscita. Riprova.',
        success: 'Grazie - il tuo feedback è stato inviato.',
        failure: 'Impossibile inviare il feedback.',
    },
    pt: {
        buttonQuestion: 'Gosta desta página?',
        buttonAriaLabel: 'Gosta desta página? Enviar feedback',
        closeLabel: 'Fechar formulário de feedback',
        eyebrow: 'Feedback da página',
        title: 'Gosta desta página?',
        intro: 'Diga-nos o que funcionou ou o que esperava, queria mudar ou adicionar.',
        yes: 'Sim',
        notReally: 'Não muito',
        feedbackLabel: 'O que devemos mudar ou adicionar?',
        feedbackPlaceholder: 'Um feedback curto e honesto é suficiente.',
        emailLabel: 'Email opcional',
        emailPlaceholder: 'Só se quiser uma resposta',
        submit: 'Enviar feedback',
        chooseRating: 'Escolha sim ou não muito.',
        negativeRequired: 'Diga-nos o que esperava, queria mudar ou adicionar.',
        captchaRequired: 'Conclua o captcha.',
        captchaFailed: 'A verificação do captcha falhou. Tente novamente.',
        success: 'Obrigado - o seu feedback foi enviado.',
        failure: 'Não foi possível enviar o feedback.',
    },
    nl: {
        buttonQuestion: 'Vind je deze pagina leuk?',
        buttonAriaLabel: 'Vind je deze pagina leuk? Geef feedback',
        closeLabel: 'Feedbackformulier sluiten',
        eyebrow: 'Paginafeedback',
        title: 'Vind je deze pagina leuk?',
        intro: 'Vertel ons wat werkte, of wat je verwachtte, wilde veranderen of toevoegen.',
        yes: 'Ja',
        notReally: 'Niet echt',
        feedbackLabel: 'Wat moeten we veranderen of toevoegen?',
        feedbackPlaceholder: 'Korte, eerlijke feedback is genoeg.',
        emailLabel: 'Email optioneel',
        emailPlaceholder: 'Alleen als je antwoord wilt',
        submit: 'Feedback verzenden',
        chooseRating: 'Kies ja of niet echt.',
        negativeRequired: 'Vertel ons wat je verwachtte, wilde veranderen of toevoegen.',
        captchaRequired: 'Vul de captcha in.',
        captchaFailed: 'Captcha-verificatie mislukt. Probeer het opnieuw.',
        success: 'Bedankt - je feedback is verzonden.',
        failure: 'Feedback verzenden is mislukt.',
    },
    pl: {
        buttonQuestion: 'Podoba Ci się ta strona?',
        buttonAriaLabel: 'Podoba Ci się ta strona? Prześlij opinię',
        closeLabel: 'Zamknij formularz opinii',
        eyebrow: 'Opinia o stronie',
        title: 'Podoba Ci się ta strona?',
        intro: 'Napisz, co zadziałało albo czego oczekiwałeś, co zmienić lub dodać.',
        yes: 'Tak',
        notReally: 'Raczej nie',
        feedbackLabel: 'Co powinniśmy zmienić lub dodać?',
        feedbackPlaceholder: 'Wystarczy krótka, szczera opinia.',
        emailLabel: 'Email opcjonalny',
        emailPlaceholder: 'Tylko jeśli chcesz odpowiedź',
        submit: 'Wyślij opinię',
        chooseRating: 'Wybierz tak albo raczej nie.',
        negativeRequired: 'Napisz, czego oczekiwałeś, co zmienić lub dodać.',
        captchaRequired: 'Uzupełnij captcha.',
        captchaFailed: 'Weryfikacja captcha nie powiodła się. Spróbuj ponownie.',
        success: 'Dziękujemy - opinia została wysłana.',
        failure: 'Nie udało się wysłać opinii.',
    },
    hu: {
        buttonQuestion: 'Tetszik ez az oldal?',
        buttonAriaLabel: 'Tetszik ez az oldal? Küldj visszajelzést',
        closeLabel: 'Visszajelzési űrlap bezárása',
        eyebrow: 'Oldal visszajelzés',
        title: 'Tetszik ez az oldal?',
        intro: 'Mondd el, mi működött, vagy mit vártál, változtatnál vagy adnál hozzá.',
        yes: 'Igen',
        notReally: 'Nem igazán',
        feedbackLabel: 'Mit változtassunk vagy adjunk hozzá?',
        feedbackPlaceholder: 'Elég egy rövid, őszinte visszajelzés.',
        emailLabel: 'Email opcionális',
        emailPlaceholder: 'Csak ha választ szeretnél',
        submit: 'Visszajelzés küldése',
        chooseRating: 'Válassz: igen vagy nem igazán.',
        negativeRequired: 'Írd meg, mit vártál, változtatnál vagy adnál hozzá.',
        captchaRequired: 'Töltsd ki a captchát.',
        captchaFailed: 'A captcha ellenőrzése sikertelen. Próbáld újra.',
        success: 'Köszönjük - a visszajelzésed elküldtük.',
        failure: 'Nem sikerült elküldeni a visszajelzést.',
    },
    ro: {
        buttonQuestion: 'Îți place această pagină?',
        buttonAriaLabel: 'Îți place această pagină? Trimite feedback',
        closeLabel: 'Închide formularul de feedback',
        eyebrow: 'Feedback despre pagină',
        title: 'Îți place această pagină?',
        intro: 'Spune-ne ce a mers sau ce te așteptai, voiai schimbat ori adăugat.',
        yes: 'Da',
        notReally: 'Nu prea',
        feedbackLabel: 'Ce ar trebui să schimbăm sau să adăugăm?',
        feedbackPlaceholder: 'Este suficient un feedback scurt și sincer.',
        emailLabel: 'Email opțional',
        emailPlaceholder: 'Doar dacă vrei un răspuns',
        submit: 'Trimite feedback',
        chooseRating: 'Alege da sau nu prea.',
        negativeRequired: 'Spune-ne ce te așteptai, voiai schimbat sau adăugat.',
        captchaRequired: 'Completează captcha.',
        captchaFailed: 'Verificarea captcha a eșuat. Încearcă din nou.',
        success: 'Mulțumim - feedbackul tău a fost trimis.',
        failure: 'Feedbackul nu a putut fi trimis.',
    },
    bg: {
        buttonQuestion: 'Харесва ли ви тази страница?',
        buttonAriaLabel: 'Харесва ли ви тази страница? Изпратете обратна връзка',
        closeLabel: 'Затваряне на формата за обратна връзка',
        eyebrow: 'Обратна връзка за страницата',
        title: 'Харесва ли ви тази страница?',
        intro: 'Кажете ни какво работи или какво очаквахте, искахте да променим или добавим.',
        yes: 'Да',
        notReally: 'Не особено',
        feedbackLabel: 'Какво да променим или добавим?',
        feedbackPlaceholder: 'Кратка и честна обратна връзка е достатъчна.',
        emailLabel: 'Email по избор',
        emailPlaceholder: 'Само ако искате отговор',
        submit: 'Изпрати обратна връзка',
        chooseRating: 'Моля, изберете да или не особено.',
        negativeRequired: 'Кажете ни какво очаквахте, искахте да променим или добавим.',
        captchaRequired: 'Попълнете captcha.',
        captchaFailed: 'Captcha проверката не бе успешна. Опитайте отново.',
        success: 'Благодарим - обратната връзка беше изпратена.',
        failure: 'Обратната връзка не можа да бъде изпратена.',
    },
    hr: {
        buttonQuestion: 'Sviđa li vam se ova stranica?',
        buttonAriaLabel: 'Sviđa li vam se ova stranica? Pošaljite povratnu informaciju',
        closeLabel: 'Zatvori obrazac za povratne informacije',
        eyebrow: 'Povratne informacije o stranici',
        title: 'Sviđa li vam se ova stranica?',
        intro: 'Recite nam što je bilo dobro ili što ste očekivali, htjeli promijeniti ili dodati.',
        yes: 'Da',
        notReally: 'Ne baš',
        feedbackLabel: 'Što bismo trebali promijeniti ili dodati?',
        feedbackPlaceholder: 'Dovoljna je kratka, iskrena povratna informacija.',
        emailLabel: 'Email nije obavezan',
        emailPlaceholder: 'Samo ako želite odgovor',
        submit: 'Pošalji povratnu informaciju',
        chooseRating: 'Odaberite da ili ne baš.',
        negativeRequired: 'Recite nam što ste očekivali, htjeli promijeniti ili dodati.',
        captchaRequired: 'Dovršite captcha provjeru.',
        captchaFailed: 'Captcha provjera nije uspjela. Pokušajte ponovno.',
        success: 'Hvala - povratna informacija je poslana.',
        failure: 'Povratnu informaciju nije bilo moguće poslati.',
    },
    sl: {
        buttonQuestion: 'Vam je ta stran všeč?',
        buttonAriaLabel: 'Vam je ta stran všeč? Pošljite povratne informacije',
        closeLabel: 'Zapri obrazec za povratne informacije',
        eyebrow: 'Povratne informacije o strani',
        title: 'Vam je ta stran všeč?',
        intro: 'Povejte nam, kaj je delovalo ali kaj ste pričakovali, želeli spremeniti ali dodati.',
        yes: 'Da',
        notReally: 'Ne ravno',
        feedbackLabel: 'Kaj naj spremenimo ali dodamo?',
        feedbackPlaceholder: 'Dovolj je kratka, iskrena povratna informacija.',
        emailLabel: 'Email ni obvezen',
        emailPlaceholder: 'Samo če želite odgovor',
        submit: 'Pošlji povratne informacije',
        chooseRating: 'Izberite da ali ne ravno.',
        negativeRequired: 'Povejte nam, kaj ste pričakovali, želeli spremeniti ali dodati.',
        captchaRequired: 'Dokončajte captcha preverjanje.',
        captchaFailed: 'Captcha preverjanje ni uspelo. Poskusite znova.',
        success: 'Hvala - povratne informacije so bile poslane.',
        failure: 'Povratnih informacij ni bilo mogoče poslati.',
    },
    sr: {
        buttonQuestion: 'Da li vam se sviđa ova stranica?',
        buttonAriaLabel: 'Da li vam se sviđa ova stranica? Pošaljite povratnu informaciju',
        closeLabel: 'Zatvori formular za povratne informacije',
        eyebrow: 'Povratne informacije o stranici',
        title: 'Da li vam se sviđa ova stranica?',
        intro: 'Recite nam šta je bilo dobro ili šta ste očekivali, želeli da promenimo ili dodamo.',
        yes: 'Da',
        notReally: 'Ne baš',
        feedbackLabel: 'Šta treba da promenimo ili dodamo?',
        feedbackPlaceholder: 'Dovoljna je kratka, iskrena povratna informacija.',
        emailLabel: 'Email nije obavezan',
        emailPlaceholder: 'Samo ako želite odgovor',
        submit: 'Pošalji povratnu informaciju',
        chooseRating: 'Izaberite da ili ne baš.',
        negativeRequired: 'Recite nam šta ste očekivali, želeli da promenimo ili dodamo.',
        captchaRequired: 'Dovršite captcha proveru.',
        captchaFailed: 'Captcha provera nije uspela. Pokušajte ponovo.',
        success: 'Hvala - povratna informacija je poslata.',
        failure: 'Povratnu informaciju nije moguće poslati.',
    },
    uk: {
        buttonQuestion: 'Вам подобається ця сторінка?',
        buttonAriaLabel: 'Вам подобається ця сторінка? Надіслати відгук',
        closeLabel: 'Закрити форму відгуку',
        eyebrow: 'Відгук про сторінку',
        title: 'Вам подобається ця сторінка?',
        intro: 'Розкажіть, що спрацювало або що ви очікували, хотіли змінити чи додати.',
        yes: 'Так',
        notReally: 'Не дуже',
        feedbackLabel: 'Що нам змінити або додати?',
        feedbackPlaceholder: 'Достатньо короткого, чесного відгуку.',
        emailLabel: 'Email необов’язково',
        emailPlaceholder: 'Лише якщо хочете відповідь',
        submit: 'Надіслати відгук',
        chooseRating: 'Виберіть так або не дуже.',
        negativeRequired: 'Розкажіть, що ви очікували, хотіли змінити чи додати.',
        captchaRequired: 'Пройдіть captcha.',
        captchaFailed: 'Перевірка captcha не вдалася. Спробуйте ще раз.',
        success: 'Дякуємо - ваш відгук надіслано.',
        failure: 'Не вдалося надіслати відгук.',
    },
    ru: {
        buttonQuestion: 'Вам нравится эта страница?',
        buttonAriaLabel: 'Вам нравится эта страница? Отправить отзыв',
        closeLabel: 'Закрыть форму отзыва',
        eyebrow: 'Отзыв о странице',
        title: 'Вам нравится эта страница?',
        intro: 'Расскажите, что понравилось или что вы ожидали, хотели изменить или добавить.',
        yes: 'Да',
        notReally: 'Не очень',
        feedbackLabel: 'Что нам изменить или добавить?',
        feedbackPlaceholder: 'Достаточно короткого честного отзыва.',
        emailLabel: 'Email необязательно',
        emailPlaceholder: 'Только если хотите ответ',
        submit: 'Отправить отзыв',
        chooseRating: 'Выберите да или не очень.',
        negativeRequired: 'Расскажите, что вы ожидали, хотели изменить или добавить.',
        captchaRequired: 'Пройдите captcha.',
        captchaFailed: 'Проверка captcha не удалась. Попробуйте снова.',
        success: 'Спасибо - ваш отзыв отправлен.',
        failure: 'Не удалось отправить отзыв.',
    },
    el: {
        buttonQuestion: 'Σας αρέσει αυτή η σελίδα;',
        buttonAriaLabel: 'Σας αρέσει αυτή η σελίδα; Στείλτε σχόλια',
        closeLabel: 'Κλείσιμο φόρμας σχολίων',
        eyebrow: 'Σχόλια για τη σελίδα',
        title: 'Σας αρέσει αυτή η σελίδα;',
        intro: 'Πείτε μας τι λειτούργησε ή τι περιμένατε, θέλατε να αλλάξει ή να προστεθεί.',
        yes: 'Ναι',
        notReally: 'Όχι ιδιαίτερα',
        feedbackLabel: 'Τι πρέπει να αλλάξουμε ή να προσθέσουμε;',
        feedbackPlaceholder: 'Αρκεί ένα σύντομο, ειλικρινές σχόλιο.',
        emailLabel: 'Email προαιρετικά',
        emailPlaceholder: 'Μόνο αν θέλετε απάντηση',
        submit: 'Αποστολή σχολίων',
        chooseRating: 'Επιλέξτε ναι ή όχι ιδιαίτερα.',
        negativeRequired: 'Πείτε μας τι περιμένατε, θέλατε να αλλάξει ή να προστεθεί.',
        captchaRequired: 'Ολοκληρώστε το captcha.',
        captchaFailed: 'Η επαλήθευση captcha απέτυχε. Δοκιμάστε ξανά.',
        success: 'Ευχαριστούμε - τα σχόλιά σας στάλθηκαν.',
        failure: 'Δεν ήταν δυνατή η αποστολή των σχολίων.',
    },
    tr: {
        buttonQuestion: 'Bu sayfayı beğendiniz mi?',
        buttonAriaLabel: 'Bu sayfayı beğendiniz mi? Geri bildirim gönderin',
        closeLabel: 'Geri bildirim formunu kapat',
        eyebrow: 'Sayfa geri bildirimi',
        title: 'Bu sayfayı beğendiniz mi?',
        intro: 'Neyin işe yaradığını veya ne beklediğinizi, neyin değişmesini ya da eklenmesini istediğinizi söyleyin.',
        yes: 'Evet',
        notReally: 'Pek değil',
        feedbackLabel: 'Neyi değiştirmeli veya eklemeliyiz?',
        feedbackPlaceholder: 'Kısa ve dürüst bir geri bildirim yeterli.',
        emailLabel: 'Email isteğe bağlı',
        emailPlaceholder: 'Yalnızca yanıt istiyorsanız',
        submit: 'Geri bildirim gönder',
        chooseRating: 'Lütfen evet veya pek değil seçin.',
        negativeRequired: 'Ne beklediğinizi, neyi değiştirmemizi veya eklememizi istediğinizi söyleyin.',
        captchaRequired: 'Lütfen captchayı tamamlayın.',
        captchaFailed: 'Captcha doğrulaması başarısız oldu. Tekrar deneyin.',
        success: 'Teşekkürler - geri bildiriminiz gönderildi.',
        failure: 'Geri bildirim gönderilemedi.',
    },
    ar: {
        buttonQuestion: 'هل أعجبتك هذه الصفحة؟',
        buttonAriaLabel: 'هل أعجبتك هذه الصفحة؟ أرسل ملاحظاتك',
        closeLabel: 'إغلاق نموذج الملاحظات',
        eyebrow: 'ملاحظات الصفحة',
        title: 'هل أعجبتك هذه الصفحة؟',
        intro: 'أخبرنا بما أعجبك أو ما كنت تتوقعه أو تريد تغييره أو إضافته.',
        yes: 'نعم',
        notReally: 'ليس كثيرًا',
        feedbackLabel: 'ما الذي يجب أن نغيره أو نضيفه؟',
        feedbackPlaceholder: 'تكفي ملاحظة قصيرة وصادقة.',
        emailLabel: 'البريد الإلكتروني اختياري',
        emailPlaceholder: 'فقط إذا كنت تريد ردًا',
        submit: 'إرسال الملاحظات',
        chooseRating: 'يرجى اختيار نعم أو ليس كثيرًا.',
        negativeRequired: 'أخبرنا بما كنت تتوقعه أو تريد تغييره أو إضافته.',
        captchaRequired: 'يرجى إكمال اختبار captcha.',
        captchaFailed: 'فشل التحقق من captcha. حاول مرة أخرى.',
        success: 'شكرًا - تم إرسال ملاحظاتك.',
        failure: 'تعذر إرسال الملاحظات.',
    },
    he: {
        buttonQuestion: 'האם אהבת את העמוד הזה?',
        buttonAriaLabel: 'האם אהבת את העמוד הזה? שליחת משוב',
        closeLabel: 'סגירת טופס המשוב',
        eyebrow: 'משוב על העמוד',
        title: 'האם אהבת את העמוד הזה?',
        intro: 'ספרו לנו מה עבד, או מה ציפיתם, רציתם לשנות או להוסיף.',
        yes: 'כן',
        notReally: 'לא ממש',
        feedbackLabel: 'מה כדאי לשנות או להוסיף?',
        feedbackPlaceholder: 'מספיק משוב קצר וכנה.',
        emailLabel: 'אימייל אופציונלי',
        emailPlaceholder: 'רק אם תרצו תשובה',
        submit: 'שליחת משוב',
        chooseRating: 'בחרו כן או לא ממש.',
        negativeRequired: 'ספרו לנו מה ציפיתם, רציתם לשנות או להוסיף.',
        captchaRequired: 'השלימו את ה-captcha.',
        captchaFailed: 'אימות ה-captcha נכשל. נסו שוב.',
        success: 'תודה - המשוב נשלח.',
        failure: 'לא הצלחנו לשלוח את המשוב.',
    },
    hi: {
        buttonQuestion: 'क्या आपको यह पेज पसंद है?',
        buttonAriaLabel: 'क्या आपको यह पेज पसंद है? प्रतिक्रिया भेजें',
        closeLabel: 'प्रतिक्रिया फ़ॉर्म बंद करें',
        eyebrow: 'पेज प्रतिक्रिया',
        title: 'क्या आपको यह पेज पसंद है?',
        intro: 'बताएं क्या अच्छा लगा, या आप क्या उम्मीद कर रहे थे, क्या बदलना या जोड़ना चाहते हैं।',
        yes: 'हाँ',
        notReally: 'ज़्यादा नहीं',
        feedbackLabel: 'हमें क्या बदलना या जोड़ना चाहिए?',
        feedbackPlaceholder: 'छोटी और ईमानदार प्रतिक्रिया काफी है।',
        emailLabel: 'Email वैकल्पिक',
        emailPlaceholder: 'केवल अगर आप उत्तर चाहते हैं',
        submit: 'प्रतिक्रिया भेजें',
        chooseRating: 'कृपया हाँ या ज़्यादा नहीं चुनें।',
        negativeRequired: 'बताएं आप क्या उम्मीद कर रहे थे, क्या बदलना या जोड़ना चाहते हैं।',
        captchaRequired: 'कृपया captcha पूरा करें।',
        captchaFailed: 'Captcha सत्यापन विफल रहा। फिर कोशिश करें।',
        success: 'धन्यवाद - आपकी प्रतिक्रिया भेज दी गई।',
        failure: 'प्रतिक्रिया भेजी नहीं जा सकी।',
    },
    ja: {
        buttonQuestion: 'このページは気に入りましたか？',
        buttonAriaLabel: 'このページは気に入りましたか？フィードバックを送信',
        closeLabel: 'フィードバックフォームを閉じる',
        eyebrow: 'ページへのフィードバック',
        title: 'このページは気に入りましたか？',
        intro: '良かった点、期待していたこと、変更や追加してほしいことを教えてください。',
        yes: 'はい',
        notReally: 'あまり',
        feedbackLabel: '何を変更または追加すべきですか？',
        feedbackPlaceholder: '短く率直なフィードバックで十分です。',
        emailLabel: 'Email 任意',
        emailPlaceholder: '返信が必要な場合のみ',
        submit: 'フィードバックを送信',
        chooseRating: '「はい」または「あまり」を選択してください。',
        negativeRequired: '期待していたこと、変更または追加してほしいことを教えてください。',
        captchaRequired: 'captcha を完了してください。',
        captchaFailed: 'captcha の確認に失敗しました。もう一度お試しください。',
        success: 'ありがとうございます - フィードバックを送信しました。',
        failure: 'フィードバックを送信できませんでした。',
    },
    ko: {
        buttonQuestion: '이 페이지가 마음에 드시나요?',
        buttonAriaLabel: '이 페이지가 마음에 드시나요? 피드백 보내기',
        closeLabel: '피드백 양식 닫기',
        eyebrow: '페이지 피드백',
        title: '이 페이지가 마음에 드시나요?',
        intro: '좋았던 점이나 기대했던 점, 바꾸거나 추가했으면 하는 점을 알려주세요.',
        yes: '예',
        notReally: '별로요',
        feedbackLabel: '무엇을 바꾸거나 추가하면 좋을까요?',
        feedbackPlaceholder: '짧고 솔직한 피드백이면 충분합니다.',
        emailLabel: 'Email 선택 사항',
        emailPlaceholder: '답변을 원할 때만 입력',
        submit: '피드백 보내기',
        chooseRating: '예 또는 별로요를 선택해 주세요.',
        negativeRequired: '기대했던 점, 바꾸거나 추가했으면 하는 점을 알려주세요.',
        captchaRequired: 'captcha를 완료해 주세요.',
        captchaFailed: 'captcha 확인에 실패했습니다. 다시 시도해 주세요.',
        success: '감사합니다 - 피드백이 전송되었습니다.',
        failure: '피드백을 보내지 못했습니다.',
    },
    zh: {
        buttonQuestion: '你喜欢这个页面吗？',
        buttonAriaLabel: '你喜欢这个页面吗？发送反馈',
        closeLabel: '关闭反馈表单',
        eyebrow: '页面反馈',
        title: '你喜欢这个页面吗？',
        intro: '告诉我们哪些内容有效，或者你期待、想修改或想添加什么。',
        yes: '喜欢',
        notReally: '不太喜欢',
        feedbackLabel: '我们应该修改或添加什么？',
        feedbackPlaceholder: '简短、真实的反馈就足够了。',
        emailLabel: 'Email 可选',
        emailPlaceholder: '仅在你希望收到回复时填写',
        submit: '发送反馈',
        chooseRating: '请选择喜欢或不太喜欢。',
        negativeRequired: '请告诉我们你期待、想修改或想添加什么。',
        captchaRequired: '请完成 captcha。',
        captchaFailed: 'Captcha 验证失败。请重试。',
        success: '谢谢 - 你的反馈已发送。',
        failure: '无法发送反馈。',
    },
    th: {
        buttonQuestion: 'คุณชอบหน้านี้ไหม?',
        buttonAriaLabel: 'คุณชอบหน้านี้ไหม? ส่งความคิดเห็น',
        closeLabel: 'ปิดแบบฟอร์มความคิดเห็น',
        eyebrow: 'ความคิดเห็นต่อหน้า',
        title: 'คุณชอบหน้านี้ไหม?',
        intro: 'บอกเราว่าอะไรดี หรือคุณคาดหวัง อยากเปลี่ยน หรืออยากเพิ่มอะไร',
        yes: 'ใช่',
        notReally: 'ไม่ค่อย',
        feedbackLabel: 'เราควรเปลี่ยนหรือเพิ่มอะไร?',
        feedbackPlaceholder: 'ความคิดเห็นสั้น ๆ และจริงใจก็เพียงพอ',
        emailLabel: 'Email ไม่บังคับ',
        emailPlaceholder: 'เฉพาะถ้าคุณต้องการคำตอบ',
        submit: 'ส่งความคิดเห็น',
        chooseRating: 'โปรดเลือกใช่หรือไม่ค่อย',
        negativeRequired: 'โปรดบอกเราว่าคุณคาดหวัง อยากเปลี่ยน หรืออยากเพิ่มอะไร',
        captchaRequired: 'โปรดทำ captcha ให้เสร็จ',
        captchaFailed: 'การตรวจสอบ captcha ล้มเหลว โปรดลองอีกครั้ง',
        success: 'ขอบคุณ - ส่งความคิดเห็นแล้ว',
        failure: 'ไม่สามารถส่งความคิดเห็นได้',
    },
    vi: {
        buttonQuestion: 'Bạn có thích trang này không?',
        buttonAriaLabel: 'Bạn có thích trang này không? Gửi phản hồi',
        closeLabel: 'Đóng biểu mẫu phản hồi',
        eyebrow: 'Phản hồi về trang',
        title: 'Bạn có thích trang này không?',
        intro: 'Hãy cho chúng tôi biết điều gì tốt, hoặc bạn mong đợi, muốn thay đổi hay thêm gì.',
        yes: 'Có',
        notReally: 'Không hẳn',
        feedbackLabel: 'Chúng tôi nên thay đổi hoặc thêm gì?',
        feedbackPlaceholder: 'Phản hồi ngắn và thật lòng là đủ.',
        emailLabel: 'Email không bắt buộc',
        emailPlaceholder: 'Chỉ khi bạn muốn nhận trả lời',
        submit: 'Gửi phản hồi',
        chooseRating: 'Vui lòng chọn có hoặc không hẳn.',
        negativeRequired: 'Hãy cho chúng tôi biết bạn mong đợi, muốn thay đổi hoặc thêm gì.',
        captchaRequired: 'Vui lòng hoàn thành captcha.',
        captchaFailed: 'Xác minh captcha thất bại. Vui lòng thử lại.',
        success: 'Cảm ơn - phản hồi của bạn đã được gửi.',
        failure: 'Không thể gửi phản hồi.',
    },
    id: {
        buttonQuestion: 'Apakah Anda suka halaman ini?',
        buttonAriaLabel: 'Apakah Anda suka halaman ini? Kirim masukan',
        closeLabel: 'Tutup formulir masukan',
        eyebrow: 'Masukan halaman',
        title: 'Apakah Anda suka halaman ini?',
        intro: 'Beri tahu kami apa yang berhasil, atau apa yang Anda harapkan, ingin ubah, atau tambahkan.',
        yes: 'Ya',
        notReally: 'Tidak terlalu',
        feedbackLabel: 'Apa yang harus kami ubah atau tambahkan?',
        feedbackPlaceholder: 'Masukan singkat dan jujur sudah cukup.',
        emailLabel: 'Email opsional',
        emailPlaceholder: 'Hanya jika Anda ingin balasan',
        submit: 'Kirim masukan',
        chooseRating: 'Pilih ya atau tidak terlalu.',
        negativeRequired: 'Beri tahu kami apa yang Anda harapkan, ingin ubah, atau tambahkan.',
        captchaRequired: 'Selesaikan captcha.',
        captchaFailed: 'Verifikasi captcha gagal. Coba lagi.',
        success: 'Terima kasih - masukan Anda telah dikirim.',
        failure: 'Gagal mengirim masukan.',
    },
    sv: {
        buttonQuestion: 'Gillar du den här sidan?',
        buttonAriaLabel: 'Gillar du den här sidan? Skicka feedback',
        closeLabel: 'Stäng feedbackformuläret',
        eyebrow: 'Feedback om sidan',
        title: 'Gillar du den här sidan?',
        intro: 'Berätta vad som fungerade, eller vad du förväntade dig, ville ändra eller lägga till.',
        yes: 'Ja',
        notReally: 'Inte riktigt',
        feedbackLabel: 'Vad borde vi ändra eller lägga till?',
        feedbackPlaceholder: 'Kort och ärlig feedback räcker.',
        emailLabel: 'Email valfritt',
        emailPlaceholder: 'Bara om du vill ha svar',
        submit: 'Skicka feedback',
        chooseRating: 'Välj ja eller inte riktigt.',
        negativeRequired: 'Berätta vad du förväntade dig, ville ändra eller lägga till.',
        captchaRequired: 'Slutför captcha.',
        captchaFailed: 'Captcha-verifieringen misslyckades. Försök igen.',
        success: 'Tack - din feedback har skickats.',
        failure: 'Det gick inte att skicka feedback.',
    },
    da: {
        buttonQuestion: 'Kan du lide denne side?',
        buttonAriaLabel: 'Kan du lide denne side? Send feedback',
        closeLabel: 'Luk feedbackformular',
        eyebrow: 'Feedback på siden',
        title: 'Kan du lide denne side?',
        intro: 'Fortæl os, hvad der virkede, eller hvad du forventede, ville ændre eller tilføje.',
        yes: 'Ja',
        notReally: 'Ikke rigtigt',
        feedbackLabel: 'Hvad skal vi ændre eller tilføje?',
        feedbackPlaceholder: 'Kort, ærlig feedback er nok.',
        emailLabel: 'Email valgfri',
        emailPlaceholder: 'Kun hvis du ønsker et svar',
        submit: 'Send feedback',
        chooseRating: 'Vælg ja eller ikke rigtigt.',
        negativeRequired: 'Fortæl os, hvad du forventede, ville ændre eller tilføje.',
        captchaRequired: 'Gennemfør captcha.',
        captchaFailed: 'Captcha-bekræftelsen mislykkedes. Prøv igen.',
        success: 'Tak - din feedback blev sendt.',
        failure: 'Feedback kunne ikke sendes.',
    },
    fi: {
        buttonQuestion: 'Pidätkö tästä sivusta?',
        buttonAriaLabel: 'Pidätkö tästä sivusta? Lähetä palautetta',
        closeLabel: 'Sulje palautelomake',
        eyebrow: 'Sivun palaute',
        title: 'Pidätkö tästä sivusta?',
        intro: 'Kerro, mikä toimi tai mitä odotit, halusit muuttaa tai lisätä.',
        yes: 'Kyllä',
        notReally: 'En oikein',
        feedbackLabel: 'Mitä meidän pitäisi muuttaa tai lisätä?',
        feedbackPlaceholder: 'Lyhyt ja rehellinen palaute riittää.',
        emailLabel: 'Email vapaaehtoinen',
        emailPlaceholder: 'Vain jos haluat vastauksen',
        submit: 'Lähetä palaute',
        chooseRating: 'Valitse kyllä tai en oikein.',
        negativeRequired: 'Kerro, mitä odotit, halusit muuttaa tai lisätä.',
        captchaRequired: 'Suorita captcha loppuun.',
        captchaFailed: 'Captcha-tarkistus epäonnistui. Yritä uudelleen.',
        success: 'Kiitos - palautteesi lähetettiin.',
        failure: 'Palautetta ei voitu lähettää.',
    },
    no: {
        buttonQuestion: 'Liker du denne siden?',
        buttonAriaLabel: 'Liker du denne siden? Send tilbakemelding',
        closeLabel: 'Lukk tilbakemeldingsskjema',
        eyebrow: 'Tilbakemelding på siden',
        title: 'Liker du denne siden?',
        intro: 'Fortell oss hva som fungerte, eller hva du forventet, ville endre eller legge til.',
        yes: 'Ja',
        notReally: 'Ikke egentlig',
        feedbackLabel: 'Hva bør vi endre eller legge til?',
        feedbackPlaceholder: 'Kort, ærlig tilbakemelding er nok.',
        emailLabel: 'Email valgfritt',
        emailPlaceholder: 'Bare hvis du ønsker svar',
        submit: 'Send tilbakemelding',
        chooseRating: 'Velg ja eller ikke egentlig.',
        negativeRequired: 'Fortell oss hva du forventet, ville endre eller legge til.',
        captchaRequired: 'Fullfør captcha.',
        captchaFailed: 'Captcha-verifisering mislyktes. Prøv igjen.',
        success: 'Takk - tilbakemeldingen din ble sendt.',
        failure: 'Kunne ikke sende tilbakemelding.',
    },
    bn: {
        buttonQuestion: 'আপনি কি এই পেজটি পছন্দ করেছেন?',
        buttonAriaLabel: 'আপনি কি এই পেজটি পছন্দ করেছেন? মতামত পাঠান',
        closeLabel: 'মতামত ফর্ম বন্ধ করুন',
        eyebrow: 'পেজ মতামত',
        title: 'আপনি কি এই পেজটি পছন্দ করেছেন?',
        intro: 'কী ভালো লেগেছে বা আপনি কী আশা করেছিলেন, কী বদলাতে বা যোগ করতে চান তা জানান।',
        yes: 'হ্যাঁ',
        notReally: 'তেমন নয়',
        feedbackLabel: 'আমাদের কী বদলানো বা যোগ করা উচিত?',
        feedbackPlaceholder: 'সংক্ষিপ্ত ও সৎ মতামতই যথেষ্ট।',
        emailLabel: 'Email ঐচ্ছিক',
        emailPlaceholder: 'শুধু উত্তর চাইলে',
        submit: 'মতামত পাঠান',
        chooseRating: 'অনুগ্রহ করে হ্যাঁ বা তেমন নয় বেছে নিন।',
        negativeRequired: 'আপনি কী আশা করেছিলেন, কী বদলাতে বা যোগ করতে চান তা জানান।',
        captchaRequired: 'অনুগ্রহ করে captcha সম্পূর্ণ করুন।',
        captchaFailed: 'Captcha যাচাই ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
        success: 'ধন্যবাদ - আপনার মতামত পাঠানো হয়েছে।',
        failure: 'মতামত পাঠানো যায়নি।',
    },
};

const hcaptchaLanguageByLocale: Record<SupportedLocale, string> = {
    ...Object.fromEntries(Object.keys(feedbackCopy).map((locale) => [locale, locale])),
    zh: 'zh-CN',
} as Record<SupportedLocale, string>;

export function getFeedbackWidgetCopy(locale: string): FeedbackWidgetCopy {
    return feedbackCopy[locale as SupportedLocale] || feedbackCopy.en;
}

export function getHcaptchaLanguage(locale: string): string {
    return hcaptchaLanguageByLocale[locale as SupportedLocale] || 'en';
}

export function getFeedbackWidgetLocales(): SupportedLocale[] {
    return Object.keys(feedbackCopy) as SupportedLocale[];
}
