import type { Browser } from 'puppeteer';

// ============================================================================
// PUPPETEER-BASED HOROSCOPE PNG GENERATOR
// Supports both local development (full Puppeteer) and Vercel (@sparticuz/chromium)
// Now supports multi-page (A4) generation for long content
// ============================================================================

// Detect if we're running on Vercel
const isVercel = process.env.VERCEL === '1' || process.env.AWS_LAMBDA_FUNCTION_NAME;

// Browser singleton with mutex to prevent concurrent access issues
let browserInstance: Browser | null = null;
let browserPromise: Promise<Browser> | null = null;
let isGenerating = false;
const generateQueue: (() => void)[] = [];

async function getBrowser(): Promise<Browser> {
    if (browserInstance) return browserInstance;

    if (!browserPromise) {
        if (isVercel) {
            // Production: Use @sparticuz/chromium for Vercel serverless
            const chromium = await import('@sparticuz/chromium');
            const puppeteerCore = await import('puppeteer-core');

            browserPromise = puppeteerCore.default.launch({
                args: chromium.default.args,
                executablePath: await chromium.default.executablePath(),
                headless: 'shell',
            }).then(browser => {
                browserInstance = browser as Browser;
                return browserInstance;
            });
        } else {
            // Local development: Use full Puppeteer
            const puppeteer = await import('puppeteer');

            browserPromise = puppeteer.default.launch({
                headless: true,
                args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--font-render-hinting=none']
            }).then(browser => {
                browserInstance = browser;
                return browser;
            });
        }
    }

    return browserPromise;
}

async function acquireLock(): Promise<void> {
    if (!isGenerating) {
        isGenerating = true;
        return;
    }
    return new Promise(resolve => {
        generateQueue.push(resolve);
    });
}

function releaseLock(): void {
    const next = generateQueue.shift();
    if (next) {
        next();
    } else {
        isGenerating = false;
    }
}

// Translations for image labels
const imageLabels: Record<string, {
    personalHoroscope: string;
    preparedFor: string;
    birthInfo: string;
    yourReading: string;
    generatedBy: string;
    allRightsReserved: string;
    pageOf?: string;
}> = {
    en: { personalHoroscope: 'Your Personal Horoscope', preparedFor: 'Prepared for', birthInfo: 'Born', yourReading: 'Your Cosmic Reading', generatedBy: 'Generated by Astralo', allRightsReserved: 'All rights reserved', pageOf: 'Page' },
    sk: { personalHoroscope: 'Váš osobný horoskop', preparedFor: 'Pripravené pre', birthInfo: 'Narodený/á', yourReading: 'Vaše kozmické čítanie', generatedBy: 'Vygenerované Astralo', allRightsReserved: 'Všetky práva vyhradené', pageOf: 'Strana' },
    cs: { personalHoroscope: 'Váš osobní horoskop', preparedFor: 'Připraveno pro', birthInfo: 'Narozen/a', yourReading: 'Vaše kosmické čtení', generatedBy: 'Vygenerováno Astralo', allRightsReserved: 'Všechna práva vyhrazena', pageOf: 'Stránka' },
    de: { personalHoroscope: 'Ihr persönliches Horoskop', preparedFor: 'Erstellt für', birthInfo: 'Geboren', yourReading: 'Ihre kosmische Lesung', generatedBy: 'Erstellt von Astralo', allRightsReserved: 'Alle Rechte vorbehalten', pageOf: 'Seite' },
    fr: { personalHoroscope: 'Votre horoscope personnel', preparedFor: 'Préparé pour', birthInfo: 'Né(e)', yourReading: 'Votre lecture cosmique', generatedBy: 'Généré par Astralo', allRightsReserved: 'Tous droits réservés', pageOf: 'Page' },
    es: { personalHoroscope: 'Tu horóscopo personal', preparedFor: 'Preparado para', birthInfo: 'Nacido/a', yourReading: 'Tu lectura cósmica', generatedBy: 'Generado por Astralo', allRightsReserved: 'Todos los derechos reservados', pageOf: 'Página' },
    it: { personalHoroscope: 'Il tuo oroscopo personale', preparedFor: 'Preparato per', birthInfo: 'Nato/a', yourReading: 'La tua lettura cosmica', generatedBy: 'Generato da Astralo', allRightsReserved: 'Tutti i diritti riservati', pageOf: 'Pagina' },
    pt: { personalHoroscope: 'O seu horóscopo pessoal', preparedFor: 'Preparado para', birthInfo: 'Nascido/a', yourReading: 'A sua leitura cósmica', generatedBy: 'Gerado por Astralo', allRightsReserved: 'Todos os direitos reservados', pageOf: 'Página' },
    nl: { personalHoroscope: 'Uw persoonlijke horoscoop', preparedFor: 'Voorbereid voor', birthInfo: 'Geboren', yourReading: 'Uw kosmische lezing', generatedBy: 'Gegenereerd door Astralo', allRightsReserved: 'Alle rechten voorbehouden', pageOf: 'Pagina' },
    pl: { personalHoroscope: 'Twój osobisty horoskop', preparedFor: 'Przygotowane dla', birthInfo: 'Urodzony/a', yourReading: 'Twoja kosmiczna lektura', generatedBy: 'Wygenerowane przez Astralo', allRightsReserved: 'Wszelkie prawa zastrzeżone', pageOf: 'Strona' },
    hu: { personalHoroscope: 'Személyes horoszkópja', preparedFor: 'Készítve', birthInfo: 'Született', yourReading: 'Kozmikus olvasása', generatedBy: 'Astralo által generálva', allRightsReserved: 'Minden jog fenntartva', pageOf: 'Oldal' },
    ro: { personalHoroscope: 'Horoscopul tău personal', preparedFor: 'Pregătit pentru', birthInfo: 'Născut/ă', yourReading: 'Lectura ta cosmică', generatedBy: 'Generat de Astralo', allRightsReserved: 'Toate drepturile rezervate', pageOf: 'Pagina' },
    bg: { personalHoroscope: 'Вашият личен хороскоп', preparedFor: 'Подготвен за', birthInfo: 'Роден/а', yourReading: 'Вашето космическо четене', generatedBy: 'Генерирано от Astralo', allRightsReserved: 'Всички права запазени', pageOf: 'Страница' },
    hr: { personalHoroscope: 'Vaš osobni horoskop', preparedFor: 'Pripremljeno za', birthInfo: 'Rođen/a', yourReading: 'Vaše kozmičko čitanje', generatedBy: 'Generirano od Astralo', allRightsReserved: 'Sva prava pridržana', pageOf: 'Stranica' },
    sl: { personalHoroscope: 'Vaš osebni horoskop', preparedFor: 'Pripravljeno za', birthInfo: 'Rojen/a', yourReading: 'Vaše kozmično branje', generatedBy: 'Ustvarjeno z Astralo', allRightsReserved: 'Vse pravice pridržane', pageOf: 'Stran' },
    uk: { personalHoroscope: 'Ваш особистий гороскоп', preparedFor: 'Підготовлено для', birthInfo: 'Народжений/а', yourReading: 'Ваше космічне читання', generatedBy: 'Створено Astralo', allRightsReserved: 'Усі права захищені', pageOf: 'Сторінка' },
    ru: { personalHoroscope: 'Ваш личный гороскоп', preparedFor: 'Подготовлено для', birthInfo: 'Рождён/а', yourReading: 'Ваше космическое чтение', generatedBy: 'Создано Astralo', allRightsReserved: 'Все права защищены', pageOf: 'Страница' },
    el: { personalHoroscope: 'Το προσωπικό σας ωροσκόπιο', preparedFor: 'Προετοιμάστηκε για', birthInfo: 'Γεννημένος/η', yourReading: 'Η κοσμική σας ανάγνωση', generatedBy: 'Δημιουργήθηκε από Astralo', allRightsReserved: 'Με επιφύλαξη παντός δικαιώματος', pageOf: 'Σελίδα' },
    tr: { personalHoroscope: 'Kişisel Burcunuz', preparedFor: 'Hazırlanan', birthInfo: 'Doğum', yourReading: 'Kozmik Okumanız', generatedBy: 'Astralo tarafından oluşturuldu', allRightsReserved: 'Tüm hakları saklıdır', pageOf: 'Sayfa' },
    ar: { personalHoroscope: 'برجك الشخصي', preparedFor: 'معد لـ', birthInfo: 'مولود', yourReading: 'قراءتك الكونية', generatedBy: 'تم إنشاؤه بواسطة Astralo', allRightsReserved: 'جميع الحقوق محفوظة', pageOf: 'صفحة' },
    he: { personalHoroscope: 'ההורוסקופ האישי שלך', preparedFor: 'הוכן עבור', birthInfo: 'נולד/ה', yourReading: 'הקריאה הקוסמית שלך', generatedBy: 'נוצר על ידי Astralo', allRightsReserved: 'כל הזכויות שמורות', pageOf: 'עמוד' },
    hi: { personalHoroscope: 'आपकी व्यक्तिगत राशिफल', preparedFor: 'के लिए तैयार', birthInfo: 'जन्म', yourReading: 'आपकी ब्रह्मांडीय रीडिंग', generatedBy: 'Astralo द्वारा निर्मित', allRightsReserved: 'सर्वाधिकार सुरक्षित', pageOf: 'पृष्ठ' },
    bn: { personalHoroscope: 'আপনার ব্যক্তিগত রাশিফল', preparedFor: 'প্রস্তুত করা হয়েছে', birthInfo: 'জন্ম', yourReading: 'আপনার মহাজাগতিক পাঠ', generatedBy: 'Astralo দ্বারা তৈরি', allRightsReserved: 'সর্বস্বত্ব সংরক্ষিত', pageOf: 'পৃষ্ঠা' },
    th: { personalHoroscope: 'ดวงส่วนตัวของคุณ', preparedFor: 'เตรียมพร้อมสำหรับ', birthInfo: 'เกิด', yourReading: 'การอ่านจักรวาลของคุณ', generatedBy: 'สร้างโดย Astralo', allRightsReserved: 'สงวนลิขสิทธิ์', pageOf: 'หน้า' },
    ja: { personalHoroscope: 'あなたの星占い', preparedFor: '作成対象', birthInfo: '生年月日', yourReading: 'あなたの宇宙的リーディング', generatedBy: 'Astralo作成', allRightsReserved: '著作権所有', pageOf: 'ページ' },
    ko: { personalHoroscope: '당신의 개인 운세', preparedFor: '대상', birthInfo: '출생', yourReading: '당신의 우주적 리딩', generatedBy: 'Astralo 제작', allRightsReserved: '모든 권리 보유', pageOf: '페이지' },
    zh: { personalHoroscope: '您的个人星座运势', preparedFor: '为您准备', birthInfo: '出生', yourReading: '您的宇宙解读', generatedBy: '由 Astralo 生成', allRightsReserved: '版权所有', pageOf: '页' },
    vi: { personalHoroscope: 'Tử vi cá nhân của bạn', preparedFor: 'Chuẩn bị cho', birthInfo: 'Sinh', yourReading: 'Bài đọc vũ trụ của bạn', generatedBy: 'Tạo bởi Astralo', allRightsReserved: 'Bảo lưu mọi quyền', pageOf: 'Trang' },
    id: { personalHoroscope: 'Horoskop pribadi Anda', preparedFor: 'Disiapkan untuk', birthInfo: 'Lahir', yourReading: 'Bacaan kosmis Anda', generatedBy: 'Dibuat oleh Astralo', allRightsReserved: 'Hak cipta dilindungi', pageOf: 'Halaman' },
    sv: { personalHoroscope: 'Ditt personliga horoskop', preparedFor: 'Förberedd för', birthInfo: 'Född', yourReading: 'Din kosmiska läsning', generatedBy: 'Genererad av Astralo', allRightsReserved: 'Alla rättigheter förbehållna', pageOf: 'Sida' },
    da: { personalHoroscope: 'Dit personlige horoskop', preparedFor: 'Forberedt til', birthInfo: 'Født', yourReading: 'Din kosmiske læsning', generatedBy: 'Genereret af Astralo', allRightsReserved: 'Alle rettigheder forbeholdes', pageOf: 'Side' },
    fi: { personalHoroscope: 'Henkilökohtainen horoskooppisi', preparedFor: 'Valmisteltu', birthInfo: 'Syntynyt', yourReading: 'Kosminen luentasi', generatedBy: 'Luonut Astralo', allRightsReserved: 'Kaikki oikeudet pidätetään', pageOf: 'Sivu' },
    no: { personalHoroscope: 'Ditt personlige horoskop', preparedFor: 'Forberedt for', birthInfo: 'Født', yourReading: 'Din kosmiske lesning', generatedBy: 'Generert av Astralo', allRightsReserved: 'Alle rettigheter reservert', pageOf: 'Side' },
    sr: { personalHoroscope: 'Vaš lični horoskop', preparedFor: 'Pripremljeno za', birthInfo: 'Rođen/a', yourReading: 'Vaše kosmičko čitanje', generatedBy: 'Generisano od Astralo', allRightsReserved: 'Sva prava zadržana', pageOf: 'Stranica' },
};

function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
}

function formatContent(content: string): string {
    return content
        .replace(/#{1,6}\s/g, '')
        .split('\n')
        .filter(p => p.trim())
        .map(p => {
            const trimmed = p.trim();
            const isHeader = trimmed.length < 60 && !trimmed.includes('.') && !trimmed.startsWith('-');
            if (isHeader) {
                return `<h3 class="section-header">${escapeHtml(trimmed)}</h3>`;
            }
            return `<p>${escapeHtml(trimmed)}</p>`;
        })
        .join('\n');
}

interface HoroscopeImageData {
    customerName: string;
    productName: string;
    horoscopeContent: string;
    birthDate: string;
    birthPlace: string;
    birthTime: string;
    lang: string;
}

// Generate HTML for a single page
function generatePageHtml(
    data: HoroscopeImageData,
    labels: typeof imageLabels['en'],
    formattedContent: string,
    pageNum: number,
    totalPages: number,
    isFirstPage: boolean
): string {
    const { customerName, productName, birthDate, birthPlace, birthTime, lang } = data;
    const isRTL = ['ar', 'he'].includes(lang);
    const width = 794;
    const height = 1123;

    // For RTL languages, use Google Noto fonts which have full Arabic/Hebrew support
    // For LTR languages, use Google Fonts for better typography
    const fontUrl = 'https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600;700&family=Noto+Sans+Bengali:wght@400;700&family=Noto+Sans+Devanagari:wght@400;700&family=Noto+Sans+Thai:wght@400;700&family=Noto+Sans+JP:wght@400;700&family=Noto+Sans+KR:wght@400;700&family=Noto+Sans+SC:wght@400;700&display=block';

    // RTL font URL - Noto Sans Arabic and Hebrew
    const rtlFontUrl = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@400;600;700&family=Noto+Sans+Hebrew:wght@400;600;700&display=block';

    // For RTL: use Google Noto fonts for proper Arabic/Hebrew rendering
    // For LTR: use Google Fonts for better aesthetics
    const fontFamily = isRTL
        ? "'Noto Sans Arabic', 'Noto Sans Hebrew', Arial, 'Segoe UI', Tahoma, sans-serif"
        : "'Noto Sans', 'Noto Sans Bengali', 'Noto Sans Devanagari', 'Noto Sans Thai', 'Noto Sans JP', 'Noto Sans KR', 'Noto Sans SC', Arial, sans-serif";

    return `
<!DOCTYPE html>
<html lang="${lang}" dir="${isRTL ? 'rtl' : 'ltr'}">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    ${isRTL
            ? `<link href="${rtlFontUrl}" rel="stylesheet">`
            : `<link href="${fontUrl}" rel="stylesheet">`}
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        html, body {
            width: ${width}px;
            height: ${height}px;
            font-family: ${fontFamily};
            background: linear-gradient(180deg, #0a0a1a 0%, #0f0f2a 30%, #1a1035 60%, #0a0a1a 100%);
            color: white;
            overflow: hidden;
        }
        
        .container {
            width: 100%;
            height: 100%;
            padding: 6px;
            position: relative;
        }
        
        .border-frame {
            width: 100%;
            height: 100%;
            border: 10px solid #fbbf24;
            position: relative;
            display: flex;
            flex-direction: column;
        }
        
        .inner-frame {
            position: absolute;
            top: 14px; left: 14px; right: 14px; bottom: 14px;
            border: 2px solid rgba(251, 191, 36, 0.4);
            pointer-events: none;
        }
        
        .stars-bg {
            position: absolute;
            width: 100%; height: 100%;
            background-image: radial-gradient(2px 2px at 10% 10%, rgba(255,255,255,0.5), transparent),
                              radial-gradient(2px 2px at 30% 20%, rgba(255,255,255,0.3), transparent),
                              radial-gradient(1px 1px at 50% 5%, rgba(255,255,255,0.6), transparent),
                              radial-gradient(2px 2px at 70% 15%, rgba(255,255,255,0.4), transparent),
                              radial-gradient(1px 1px at 90% 8%, rgba(255,255,255,0.5), transparent),
                              radial-gradient(2px 2px at 15% 80%, rgba(255,255,255,0.3), transparent),
                              radial-gradient(1px 1px at 85% 85%, rgba(255,255,255,0.5), transparent);
            pointer-events: none;
        }
        
        .nebula {\r
            position: absolute;\r
            border-radius: 50%;\r
            filter: blur(60px);\r
            pointer-events: none;\r
        }\r
        .nebula-1 { width: 250px; height: 250px; top: 5%; left: 10%; background: rgba(138, 43, 226, 0.12); }\r
        .nebula-2 { width: 200px; height: 200px; top: 20%; right: 5%; background: rgba(75, 0, 130, 0.1); }\r
        \r
        /* Zodiac constellation decorations */\r
        .constellation {\r
            position: absolute;\r
            pointer-events: none;\r
            opacity: 0.25;\r
        }\r
        .constellation-top-right {\r
            top: 60px; right: 30px;\r
            width: 120px; height: 120px;\r
        }\r
        .constellation-bottom-left {\r
            bottom: 80px; left: 30px;\r
            width: 100px; height: 100px;\r
        }\r
        .constellation svg {\r
            width: 100%;\r
            height: 100%;\r
            fill: none;\r
            stroke: rgba(251, 191, 36, 0.6);\r
            stroke-width: 1;\r
        }\r
        .constellation circle {\r
            fill: rgba(251, 191, 36, 0.8);\r
        }\r
        \r
        /* Gold corner accents */\r
        .corner-accent {\r
            position: absolute;\r
            width: 40px;\r
            height: 40px;\r
            border: 2px solid rgba(251, 191, 36, 0.3);\r
            pointer-events: none;\r
        }\r
        .corner-tl { top: 30px; left: 30px; border-right: none; border-bottom: none; }\r
        .corner-tr { top: 30px; right: 30px; border-left: none; border-bottom: none; }\r
        .corner-bl { bottom: 30px; left: 30px; border-right: none; border-top: none; }\r
        .corner-br { bottom: 30px; right: 30px; border-left: none; border-top: none; }
        
        .header {
            text-align: center;
            padding: ${isFirstPage ? '25px' : '15px'} 20px 15px;
        }
        
        .stars-decoration { color: #fbbf24; font-size: 14px; letter-spacing: 10px; margin-bottom: 10px; }
        
        .logo {
            font-size: ${isFirstPage ? '42px' : '28px'};
            font-weight: 700;
            color: #fbbf24;
            text-shadow: 0 0 25px rgba(251, 191, 36, 0.5);
            letter-spacing: 3px;
        }
        
        .subtitle { font-size: 14px; color: rgba(255, 255, 255, 0.7); margin-top: 8px; }
        
        .badge-container { display: flex; justify-content: center; margin: 15px 0; }
        
        .product-badge {
            display: inline-block;
            padding: 10px 28px;
            border: 2px solid #fbbf24;
            border-radius: 22px;
            background: rgba(251, 191, 36, 0.12);
            color: #fbbf24;
            font-size: 16px;
            font-weight: 600;
        }
        
        .customer-card {
            margin: 12px 28px;
            padding: 16px 22px;
            background: linear-gradient(135deg, rgba(251, 191, 36, 0.08) 0%, rgba(147, 51, 234, 0.04) 100%);
            border: 1.5px solid rgba(251, 191, 36, 0.35);
            border-radius: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .customer-info .label { color: rgba(251, 191, 36, 0.85); font-size: 13px; margin-bottom: 4px; }
        .customer-info .name { color: white; font-size: 20px; font-weight: 700; }
        .birth-info { text-align: ${isRTL ? 'left' : 'right'}; color: rgba(255, 255, 255, 0.55); font-size: 13px; line-height: 1.5; }
        
        .content {
            flex: 1;
            padding: 15px 32px;
            overflow: hidden;
        }
        
        .reading-header {
            color: #fbbf24;
            font-size: 18px;
            font-weight: 700;
            margin-bottom: 6px;
            padding-bottom: 6px;
            border-bottom: 2px solid rgba(251, 191, 36, 0.35);
            display: inline-block;
        }
        
        .reading-content { margin-top: 15px; line-height: 1.65; }
        .reading-content p { margin-bottom: 12px; color: rgba(255, 255, 255, 0.9); font-size: 15px; }
        .reading-content .section-header {
            color: rgba(251, 191, 36, 0.92);
            font-size: 16px;
            font-weight: 600;
            margin: 16px 0 8px;
        }
        
        .footer {
            padding: 15px 28px;
            text-align: center;
            border-top: 1px solid rgba(251, 191, 36, 0.25);
            margin: 0 50px;
        }
        
        .footer-stars { color: #fbbf24; font-size: 11px; margin-bottom: 8px; }
        .footer-text { color: rgba(255, 255, 255, 0.45); font-size: 11px; line-height: 1.5; }
        .page-number { color: rgba(255, 255, 255, 0.6); font-size: 12px; margin-top: 5px; }
        
        .continuation-notice {
            text-align: center;
            color: rgba(251, 191, 36, 0.7);
            font-size: 13px;
            padding: 10px;
            margin: 10px 30px 0;
            border: 1px dashed rgba(251, 191, 36, 0.3);
            border-radius: 8px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="border-frame">
            <div class="inner-frame"></div>
            ${!isRTL ? `
            <div class="nebula nebula-1"></div>
            <div class="nebula nebula-2"></div>
            <div class="stars-bg"></div>
            
            <!-- Zodiac constellation decoration (top-right) - simplified Aries -->
            <div class="constellation constellation-top-right">
                <svg viewBox="0 0 100 100">
                    <circle cx="20" cy="30" r="3"/>
                    <circle cx="50" cy="20" r="4"/>
                    <circle cx="80" cy="35" r="3"/>
                    <circle cx="45" cy="60" r="3"/>
                    <circle cx="70" cy="80" r="4"/>
                    <line x1="20" y1="30" x2="50" y2="20"/>
                    <line x1="50" y1="20" x2="80" y2="35"/>
                    <line x1="50" y1="20" x2="45" y2="60"/>
                    <line x1="45" y1="60" x2="70" y2="80"/>
                </svg>
            </div>
            
            <!-- Zodiac constellation decoration (bottom-left) - simplified Gemini -->
            <div class="constellation constellation-bottom-left">
                <svg viewBox="0 0 100 100">
                    <circle cx="25" cy="20" r="3"/>
                    <circle cx="75" cy="20" r="3"/>
                    <circle cx="30" cy="50" r="2"/>
                    <circle cx="70" cy="50" r="2"/>
                    <circle cx="25" cy="80" r="3"/>
                    <circle cx="75" cy="80" r="3"/>
                    <line x1="25" y1="20" x2="30" y2="50"/>
                    <line x1="30" y1="50" x2="25" y2="80"/>
                    <line x1="75" y1="20" x2="70" y2="50"/>
                    <line x1="70" y1="50" x2="75" y2="80"/>
                    <line x1="30" y1="50" x2="70" y2="50"/>
                </svg>
            </div>
            
            <!-- Corner accents -->
            <div class="corner-accent corner-tl"></div>
            <div class="corner-accent corner-tr"></div>
            <div class="corner-accent corner-bl"></div>
            <div class="corner-accent corner-br"></div>
            ` : ''}
            
            <div class="header">
                <div class="stars-decoration">✦ ✧ ★ ✧ ✦</div>
                <div class="logo">ASTRALO</div>
                ${isFirstPage ? `<div class="subtitle">${escapeHtml(labels.personalHoroscope)}</div>` : ''}
            </div>
            
            ${isFirstPage ? `
            <div class="badge-container">
                <div class="product-badge">${escapeHtml(productName)}</div>
            </div>
            
            <div class="customer-card">
                <div class="customer-info">
                    <div class="label">${escapeHtml(labels.preparedFor)}</div>
                    <div class="name">${escapeHtml(customerName)}</div>
                </div>
                <div class="birth-info">
                    ${escapeHtml(labels.birthInfo)}: ${escapeHtml(birthDate)}<br>
                    ${escapeHtml(birthTime)} • ${escapeHtml(birthPlace)}
                </div>
            </div>
            ` : `
            <div class="continuation-notice">
                ${escapeHtml(labels.yourReading)} - ${escapeHtml(labels.pageOf || 'Page')} ${pageNum}/${totalPages}
            </div>
            `}
            
            <div class="content">
                ${isFirstPage ? `<div class="reading-header">${escapeHtml(labels.yourReading)}</div>` : ''}
                <div class="reading-content">
                    ${formattedContent}
                </div>
            </div>
            
            <div class="footer">
                <div class="footer-stars">★</div>
                <div class="footer-text">
                    ${escapeHtml(labels.generatedBy)}<br>
                    © 2024 astralo.online • ${escapeHtml(labels.allRightsReserved)}
                </div>
                ${totalPages > 1 ? `<div class="page-number">${escapeHtml(labels.pageOf || 'Page')} ${pageNum} / ${totalPages}</div>` : ''}
            </div>
        </div>
    </div>
</body>
</html>`;
}


export async function generateHoroscopeImage(data: HoroscopeImageData): Promise<{ filename: string; content: Buffer }[]> {
    const { lang, horoscopeContent } = data;

    const labels = imageLabels[lang] || imageLabels.en;
    const formattedContent = formatContent(horoscopeContent);
    const isRTL = ['ar', 'he'].includes(lang);

    // A4 dimensions at 96 DPI
    const width = 794;
    const height = 1123;

    await acquireLock();

    let page = null;
    let rtlBrowserInstance: any = null;  // Declared outside try for cleanup
    const results: { filename: string; content: Buffer }[] = [];

    try {
        // For RTL languages, use a FRESH browser instance
        // The shared browser has cached state that breaks RTL rendering
        let browser;

        if (isRTL) {
            if (isVercel) {
                // Vercel: Use @sparticuz/chromium
                const chromium = await import('@sparticuz/chromium');
                const puppeteerCore = await import('puppeteer-core');
                rtlBrowserInstance = await puppeteerCore.default.launch({
                    args: chromium.default.args,
                    executablePath: await chromium.default.executablePath(),
                    headless: 'shell',
                });
            } else {
                // Local: Use full Puppeteer
                const puppeteer = await import('puppeteer');
                rtlBrowserInstance = await puppeteer.default.launch({
                    headless: true,
                    args: ['--no-sandbox', '--disable-setuid-sandbox']
                });
            }
            browser = rtlBrowserInstance;
        } else {
            browser = await getBrowser();
        }

        page = await browser.newPage();
        await page.setViewport({ width, height, deviceScaleFactor: 1 });

        // First, render the full content to measure its height
        // The generatePageHtml template already handles RTL with dir="rtl" and proper font-family
        const measureHtml = generatePageHtml(data, labels, formattedContent, 1, 1, true);

        // For RTL languages, use data URL approach which works better across environments
        // The file:// approach doesn't work well on serverless
        if (isRTL) {
            // Convert HTML to base64 data URL
            const base64Html = Buffer.from(measureHtml, 'utf-8').toString('base64');
            const dataUrl = `data:text/html;charset=utf-8;base64,${base64Html}`;

            await page.goto(dataUrl, {
                waitUntil: 'networkidle0',
                timeout: 60000
            });

            console.log(`📷 RTL PNG: Loaded HTML for ${lang}, waiting for fonts...`);
        } else {
            await page.setContent(measureHtml, {
                waitUntil: 'domcontentloaded',
                timeout: 30000
            });
        }

        // Wait for fonts to be ready (system fonts should be instant)
        await page.evaluate(() => document.fonts.ready);

        // Wait for rendering - longer for RTL to ensure fonts load
        if (isRTL) {
            await new Promise(resolve => setTimeout(resolve, 3000));
        } else {
            await new Promise(resolve => setTimeout(resolve, 500));
        }

        // Get the actual content height
        const contentHeight = await page.evaluate(() => {
            const content = document.querySelector('.reading-content');
            return content ? content.scrollHeight : 0;
        });

        console.log(`📷 PNG: Content height for ${lang}: ${contentHeight}px`);

        // For RTL, if contentHeight is 0, something is wrong - try getting body height instead
        let effectiveContentHeight = contentHeight;
        if (isRTL && contentHeight === 0) {
            effectiveContentHeight = await page.evaluate(() => {
                const body = document.body;
                return body ? body.scrollHeight : 0;
            });
            console.log(`📷 RTL PNG: Fallback body height: ${effectiveContentHeight}px`);
        }

        // Estimate available content space per page (roughly 700px for first page, 850px for subsequent)
        const firstPageContentSpace = 650;
        const subsequentPageContentSpace = 800;

        // Split content into paragraphs
        const paragraphs = horoscopeContent.split('\n').filter(p => p.trim());

        // Determine if we need multiple pages
        if (effectiveContentHeight <= firstPageContentSpace || effectiveContentHeight === 0) {
            // Single page - take screenshot
            // For RTL, take screenshot without clip (required for RTL rendering to work)
            let buffer: Buffer;
            if (isRTL) {
                buffer = await page.screenshot({ type: 'png' }) as Buffer;
            } else {
                buffer = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width, height } }) as Buffer;
            }
            const datePart = new Date().toISOString().split('T')[0];
            results.push({ filename: `Horoscope_${datePart}.png`, content: buffer });
        } else {
            // Multiple pages needed
            // Split paragraphs into chunks that fit each page
            const chunks: string[][] = [];
            let currentChunk: string[] = [];
            let currentHeight = 0;
            const avgCharHeight = 20; // Rough estimate per line
            const charsPerLine = 70;

            for (const para of paragraphs) {
                const lines = Math.ceil(para.length / charsPerLine);
                const paraHeight = lines * avgCharHeight + 20; // + spacing

                const maxHeight = chunks.length === 0 ? firstPageContentSpace : subsequentPageContentSpace;

                if (currentHeight + paraHeight > maxHeight && currentChunk.length > 0) {
                    chunks.push(currentChunk);
                    currentChunk = [para];
                    currentHeight = paraHeight;
                } else {
                    currentChunk.push(para);
                    currentHeight += paraHeight;
                }
            }
            if (currentChunk.length > 0) {
                chunks.push(currentChunk);
            }

            const totalPages = chunks.length;
            const datePart = new Date().toISOString().split('T')[0];

            // Generate each page
            for (let i = 0; i < chunks.length; i++) {
                const chunkContent = formatContent(chunks[i].join('\n'));
                const pageHtml = generatePageHtml(data, labels, chunkContent, i + 1, totalPages, i === 0);

                // For RTL, use data URL approach for consistent behavior
                if (isRTL) {
                    // Convert HTML to base64 data URL (same as measurement)
                    const base64Html = Buffer.from(pageHtml, 'utf-8').toString('base64');
                    const dataUrl = `data:text/html;charset=utf-8;base64,${base64Html}`;

                    await page.goto(dataUrl, {
                        waitUntil: 'networkidle0',
                        timeout: 60000
                    });
                } else {
                    await page.setContent(pageHtml, {
                        waitUntil: 'domcontentloaded',
                        timeout: 30000
                    });
                }
                await page.evaluate(() => document.fonts.ready);
                await new Promise(resolve => setTimeout(resolve, isRTL ? 4000 : 300));

                // For RTL, don't use clip as it can cause rendering issues
                let buffer: Buffer;
                if (isRTL) {
                    buffer = await page.screenshot({ type: 'png' }) as Buffer;
                } else {
                    buffer = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width, height } }) as Buffer;
                }
                results.push({
                    filename: totalPages > 1 ? `Horoscope_${datePart}_Page${i + 1}.png` : `Horoscope_${datePart}.png`,
                    content: buffer
                });
            }
        }


        return results;
    } catch (error) {
        console.error(`❌ Error generating horoscope image for ${lang}:`, error);
        throw error;
    } finally {
        if (page) {
            try { await page.close(); } catch (e) { /* ignore */ }
        }
        // Close fresh RTL browser if we created one
        if (isRTL && rtlBrowserInstance) {
            try { await rtlBrowserInstance.close(); } catch (e) { /* ignore */ }
        }
        releaseLock();
    }
}
